### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by rhysperry111** [candreslobor/dotfiles#1]
You haven't included .config/Xresources folder which contains quite alot of vital stuff

**Comment by candreslobor** [comment]
I had not noticed that, I will try to solve it as soon as possible

**Comment by candreslobor** [comment]
You can also take a look to those files here 

https://github.com/candreslobor/dotfiles/tree/99fb7084fb8e06e05600652455caa624b91269e2/.config/Xresources
